name: Test Secret Extraction

on: [push]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and Test Secrets
        run: |
          echo "Extracting KV Secrets"
          for secret_name in $(echo "${{ toJSON(secrets) }}" | jq -r 'keys[] | select(startswith("KV_"))'); do
            # Acceder al valor del secreto en el contexto de Bash
            secret_value=${{ secrets[secret_name] }}

            echo "Processing secret: $secret_name"
            echo "Value (hidden): [REDACTED]"  # No imprimas el valor real por seguridad
          done
