name: Test Secret Extraction

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nombre del entorno'
        required: true
        default: 'development'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print all secrets
        run: |
          echo "All secrets: ${{ toJSON(secrets) }}"

      - name: Extract KV Secrets
        run: |
          echo "Extracting KV Secrets for the environment: ${{ github.event.inputs.environment }}"

          # Obtener los nombres de los secretos que comienzan con "KV_"
          secrets_list=$(echo "${{ toJSON(secrets) }}" | jq -r 'keys[] | select(startswith("KV_"))')

          # Comprobar si se encontraron secretos
          if [ -z "$secrets_list" ]; then
            echo "No KV_ secrets found."
            exit 0
          fi

          # Iterar sobre la lista de secretos
          for secret_name in $secrets_list; do
            echo "Processing secret: $secret_name"
          done
