name: Test Secret Extraction

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nombre del entorno'
        required: true
        default: 'development'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract KV Secrets
        run: |
          echo "Extracting KV Secrets for the environment: ${{ github.event.inputs.environment }}"

          # Obtener los nombres de los secretos que comienzan con "KV_"
          secrets_list=$(echo "${{ toJSON(secrets) }}" | jq -r 'keys[] | select(startswith("KV_"))')

          # Iterar sobre la lista de secretos
          for secret_name in $secrets_list; do
            echo "Processing secret: $secret_name"
            # Aquí podrías realizar más acciones si fuera necesario
          done
