name: Test Secret Extraction

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nombre del entorno'
        required: true
        default: 'development'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract and Test Secrets
        run: |
          echo "Extracting KV Secrets for the environment: ${{ github.event.inputs.environment }}"

          # Imprimir todos los secretos que comienzan con "KV_"
          for secret_name in $(echo "${{ toJSON(secrets) }}" | jq -r 'keys[] | select(startswith("KV_"))'); do
            echo "Processing secret: $secret_name"
            # Accede al secreto a través de la expresión de shell
            secret_value=$(eval echo \${{ secrets.$secret_name }})

            echo "Value (hidden): [REDACTED]"  # No imprimas el valor real por seguridad
          done
